### ISSUE TITLE
deal with edisgo storage distribution in eGo

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGo#103]
Once storages are distributed in edisgo I suggest that those costs should be assigned to the edisgo voltage levels and equally substracted from the etrago specific investment costs.
So far only the grid expansion costs are processed (see [edisgo_grid_investment()](https://github.com/openego/eGo/blob/dev/ego/tools/economics.py#L349))

@maltesc what do you think?

**Comment by maltesc** [comment]
The cost distribution for storage units in MV grids is now implemented in dev.

By default, the dataframe https://github.com/openego/eGo/blob/6d4d48aa958156fd0038d84f3769bf899936d0a8/ego/tools/io.py#L479 is now modified with https://github.com/openego/eGo/blob/6d4d48aa958156fd0038d84f3769bf899936d0a8/ego/tools/io.py#L486 in order to allocate a certain amount of storages tto MV grids. 

The plotting function https://github.com/openego/eGo/blob/6d4d48aa958156fd0038d84f3769bf899936d0a8/ego/tools/io.py#L638 thereby automatically includes the allocated storage.
