### ISSUE TITLE
Plotting for eGo

### ISSUE THREAD

**Issue by maltesc** [openego/eGo#19]
I open this issue in order to discuss and develop useful plots for eGo.

**Comment by wolfbunke** [comment]
For a dynamic plotting I was testing ipolt() of PYPSA which is based on plotly and its plot[ type scatter.](https://github.com/PyPSA/PyPSA/blob/master/pypsa/plot.py#L331)  Using this [function ]( https://plot.ly/python/line-and-scatter/) with a large scenario like Status Quo ends up in a crash of the memory (in my case 32Gib) due to the large input of data.

A solution of this could be the use of Scattergl() in place of Scatter(). An other problem which is not solved yet is that network.iplot() can only be used in iPython / jupyter notebook. 

The package folium (folium==0.5.0+98.g106d829) is using the library of leafletjs.com with OSM as map. A first plotting function igeoplot is now implemented in[ plots.py ](https://github.com/openego/eGo/blob/dev/ego/tools/plots.py#L54) which works faster at the moment.

**Comment by wolfbunke** [comment]
After changing the eGo classes the interactive plot function has to be over-worked. Since folium's stable version for pip is v0.5.0. This package should replaced by plotly  or the like.

**Comment by wolfbunke** [comment]
Folium 0.6 is released. And the function ego.iplot is now implemented in features/change-settings.
Also I cleaned up outdated plots.

Missing plots are:
ego.cluster_distribution  # (eDisGo+eTraGo)
ego.cost_distribution
and more ...?
