### ISSUE TITLE
eDisGo and Ding0 integration

### ISSUE THREAD

**Issue by wolfbunke** [openego/eGo#27]
For the further development of eGo we need to implement eDisGo with an iterative functionality which allows us to calculated all or clustered/ chosen ding0 grids.

Following questions and task should be solved:
- creation, storage (oedb, pickle, csv) and integration of multiple dingo grids
- allocation of function and implementation (What is part of eDisGo / eGo )
- How to implement the iteration function in term of calc. Speed / use of precalculated results ?
- calculation of the total system costs (investment + operating costs) of grids and storages
- ...

**Comment by gplssm** [comment]
As this is quite a large topic, I would suggest to use our regular _Schnittstellen-Telko_ as kick-off. It would be really nice if you have prepared questions you need answers for and specific tasks/questions to specific people.

**Comment by maltesc** [comment]
For my Master thesis I already implemented a eDisGo iteration (see [here](https://github.com/openego/eGo/blob/features/corr/ego/corr_edisgo.py)). 

Of course, the code is quite specific for my thesis (e.g. I only extract results that are important for my analyses). However, it might serve as an orientation.

**Comment by maltesc** [comment]
I have a question regarding the ding0 integration in eGo.
In order to use the eGo package, ding0 grids (MV grids) are required. Thus, the user must create them beforehand. Currently, the ding0 usage examples (https://github.com/openego/ding0/tree/dev/ding0/examples) don't work with the eGo installation. Instead, I had to use an independent ding0 installation in order to create the grids. 

I am wondering if the creation of grids should be part of eGo? Or will this be provided via the oedb in the future? This has probably been discussed before. @wolfbunke and @gplssm, could you tell me how this is intended to be?
