### ISSUE TITLE
Implement a function for the uniform annualization of investment costs

### ISSUE THREAD

**Issue by wolfbunke** [openego/eGo#36]
Implement a function for the uniform annualization of investment costs in order to get a standardized cost calculation of eTraGo and eDisGo cost calculations

See more on redmine protocol

**Comment by wolfbunke** [comment]
Based on the eDisGo file [config_grid_expansion_default.cfg](https://github.com/openego/eDisGo/blob/dev/edisgo/config/config_grid_expansion_default.cfg#L77-L102) we need for the equipment additional parameter of the lifetime per equipment (Trafo / Cable). The best would be to read the original config file from eDisGo. 

As fare I can see we need the lifetime of:

> hv_mv_transformer = 40 MVA
> mv_lv_transformer = 630 kVA
> mv_line = NA2XS2Y 3x1x185 RM/25
> lv_line = NAYY 4x1x150

@birgits and @gplssm  do you have maybe this information?

**Comment by wolfbunke** [comment]
@maltesc  we get the data with following script: 

```
import os, edisgo
config = os.path.join(edisgo.__path__[0], 'config', 'config_grid_expansion_default.cfg')

try:
    import configparser as cp
except:
    # to be compatible with Python2.7
    import ConfigParser as cp

cfg = cp.RawConfigParser()
cfg.read(config)

for key, value in cfg.items('grid_expansion_standard_equipment'):
    print(key)
    print(value)
```

**Comment by birgits** [comment]
As far as I can see neither DENA nor the Baden-Württemberg distribution grid study that our grid expansion measures are based on give any information on lifetimes. In a former project we used lifetimes given in a paper by Stetz ([Techno-economic assessment of voltage control strategies in low voltage grids](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6839068). They're using 40 years for cables and transformers (this does only include MV/LV transformers since they don't consider HV/MV transformers).

**Comment by birgits** [comment]
I also remember that there was a redmine ticket on this but unfortunately don't remember what to search for to find it...

**Comment by birgits** [comment]
Sorry, I meant this [ticket](http://oep.iks.cs.ovgu.de/redmine/projects/open_ego/wiki/Annahmen_zu_installierbaren_Speichern_(AP_33)) and it's only concerned with storages. Still relevant for this issue though in case you forgot about it.

**Comment by wolfbunke** [comment]
The function is implemented in https://github.com/openego/eGo/blob/dev/ego/tools/economics.py#L63
