### ISSUE TITLE
release 0.3

### ISSUE THREAD

**Issue by ulfmueller** [openego/eGo#96]
I would like to schedule a last major release of eGo respectively eTraGo, eDisGo, ding0, ego.io within the project of open_eGo. 

I propose to have a 'release week'.
Tuesday: ego.io
Wednesday: eTraGo, ding0
Thursday: eDisGo
Friday: eGo

From my side I suggest the 3.-7. or 24. -28 of September.

What do you think?

**Comment by birgits** [comment]
Very good idea and I would say rather sooner than later, so I vote for beginning of September. We also need to add ding0 to the list. We can release it on Wednesday as well as it needs the ego.io release and eDisGo needs the ding0 release.

**Comment by BartelsJ** [comment]
I totally agree with that. Unfortunately I am absent at both weeks.. I also prefer the week at the beginning of September.

**Comment by wolfbunke** [comment]
Both dates are ok for me

**Comment by birgits** [comment]
I can release ding0 and eDisGo.

**Comment by maltesc** [comment]
First week of September is good for me!
I see @wolfbunke and me primarily in the eGo section...

**Comment by birgits** [comment]
ding0 is released :) Everything should be working but let me know if there are any issues with the new release.

**Comment by ulfmueller** [comment]
The etrago release is a bit delayed. We are in the last testing phase. I'll release it today at approx. 10 am.

**Comment by birgits** [comment]
I pushed all changes to be included in the edisgo release to dev. @maltesc already tested them but if anyone else wants to test please do so and let me know if anything's not working. I will do the actual release tonight.

**Comment by ulfmueller** [comment]
The eTraGo release 0.7.0 is uploaded by pypi and should work.

**Comment by birgits** [comment]
eDisGo release 0.0.6 is uploaded as well!

**Comment by wolfbunke** [comment]
eGo 0.3.0 is released since Friday! Unfortunately the pypsa fork hack in the setup.py doesn't work any more with pip 18 therefore I copied the pypsa 0.11 fork into eGo. See here:  https://github.com/openego/eGo/tree/features/plots. This integration works now on test.pypi.org. @ulfmueller  @BartelsJ are you OK with this solution? The same issue effects with the setup.py of eTraGo. 

You can test it with:
`
pip3 install --index-url https://test.pypi.org/simple/ ego==0.3.0.24 --process-dependency-links  --extra-index-url https://pypi.org/simple --process-dependency-links`

**Comment by wolfbunke** [comment]
new Release ticket: #141
